// Oracle for Task 1 — the Secret type. This is the done-signal: make it green by
// writing include/keyward/secret.hpp. Do not edit this file to pass.
#include "keyward/secret.hpp"

#include <gtest/gtest.h>

#include <string>
#include <string_view>
#include <type_traits>
#include <utility>

using keyward::Secret;

TEST(Secret, HoldsAndBorrows) {
  Secret s("hunter2");
  EXPECT_EQ(s.view(), "hunter2");
  EXPECT_EQ(s.size(), 7u);
  EXPECT_FALSE(s.empty());

  Secret e("");
  EXPECT_TRUE(e.empty());
  EXPECT_EQ(e.size(), 0u);
}

TEST(Secret, RedactsAndNeverRevealsBytes) {
  Secret s("hunter2");
  const std::string r = s.redacted();
  EXPECT_EQ(r.find("hunter2"), std::string::npos);  // the plaintext must NOT appear
  EXPECT_FALSE(r.empty());                           // but there is *some* masked marker
}

TEST(Secret, IsMoveOnly) {
  static_assert(!std::is_copy_constructible_v<Secret>, "Secret must not be copyable");
  static_assert(!std::is_copy_assignable_v<Secret>, "Secret must not be copy-assignable");
  static_assert(std::is_move_constructible_v<Secret>, "Secret must be movable");
  static_assert(std::is_nothrow_move_constructible_v<Secret>, "move must be noexcept");
  SUCCEED();
}

TEST(Secret, MoveTransfersAndClearsSource) {
  Secret s("abc");
  Secret t = std::move(s);
  EXPECT_EQ(t.view(), "abc");  // value moved into t
  EXPECT_TRUE(s.empty());      // moved-from source is cleared
}
